[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "gzip"

# Enable compression
[build.environment]
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
