[build]
  publish = "dist"
  command = "npm run build"

# Force clean deploy
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers with proper caching
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
